### ISSUE TITLE
How about using OpenSuse Tumbleweed for WSL2?

### ISSUE THREAD

**Issue by cnmade** [rancher-sandbox/rancher-desktop-wsl-distro#24]
How about using OpenSuse Tumbleweed for WSL2?
I am currently using OpenSuse Tumbleweed for WSL2 , It already support podman, working perfect.
alpine looks too small , and now it's now working for my test. 
I am try rancher desktop + windows 11 + WSL2.
but got failed to run them.

**Comment by cnmade** [comment]
I guess the rancher team has fewer resources to maintain a full linux distro.
Why not join big OpenSuse family together. 
I love OpenSuse more than alphine , and it's really a full feature and tested linux distro i think.

**Comment by mook-as** [comment]
This distribution is only meant for use with Rancher Desktop, and not a general distribution; as such, we're aiming for it to be minimal.  As such, this being "too small" (but still enough for Rancher Desktop) seems desirable.

We've looked at podman before, but due to compatibility concerns we've decided to not go down that route.

Generally speaking, we like OpenSUSE (my office machine is running Leap), but we've had issues getting it to be minimal. The appropriate [BCI](https://registry.suse.com/static/suse/sle15sp3/index.html) still contains things we have no need of like Kerberos support and `pam`.  It would be good for interactive use and to emulate a proper Linux installation, but that's not what we need here.

Thanks for your comments, but at the moment we're probably not going to switch unless there's a PR that demonstrates an OpenSUSE base image with similar size, or other significant advantages.
